name: Deploy
# Trigger workflow manually using the GitHub UI
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 'v2.1.4'  

      - name: Check Deno version
        run: deno -v

      # Step 3: Use GitHub Secrets (stored in the repository settings)
      - name: Set environment variables from GitHub Secrets
        run: |
          # Server
          echo "SERVER_AUTH_USERNAME=${{ secrets.SERVER_AUTH_USERNAME }}" | tee -a .env
          echo "SERVER_AUTH_PASSWORD=${{ secrets.SERVER_AUTH_PASSWORD }}" | tee -a .env

          # Client
          echo "CLIENT_AUTH_USERNAME=${{ secrets.CLIENT_AUTH_USERNAME }}" | tee -a .env
          echo "CLIENT_AUTH_PASSWORD=${{ secrets.CLIENT_AUTH_PASSWORD }}" | tee -a .env

          # Binance
          echo "BINANCE_BASE_URL=${{ secrets.BINANCE_BASE_URL }}" | tee -a .env
          echo "BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}" | tee -a .env

          # Supabase
          echo "SUPABASE_CONNECTION_URL=${{ secrets.SUPABASE_CONNECTION_URL }}" | tee -a .env
          echo "SUPABASE_REST_URL=${{ secrets.SUPABASE_REST_URL }}" | tee -a .env
          echo "SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}" | tee -a .env

      # Debugging: Check contents of .env file
      - name: Check contents of .env
        run: cat .env

      # Step 4: Run your Deno application
      - name: Run Deno main.ts
        run: |
          deno run --allow-env --allow-read --allow-net main.ts
