name: Deploy
# Trigger workflow manually using the GitHub UI
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 'v2.1.4'  

      - name: Check Deno version
        run: deno -v

      # Step 3: Use GitHub env (stored in the repository settings)
      - name: Set environment variables from GitHub env
        run: |
          # Server
          echo "SERVER_AUTH_USERNAME=${{ vars .SERVER_AUTH_USERNAME }}"
          echo "SERVER_AUTH_PASSWORD=${{ vars .SERVER_AUTH_PASSWORD }}"

          # Client
          echo "CLIENT_AUTH_USERNAME=${{ vars .CLIENT_AUTH_USERNAME }}"
          echo "CLIENT_AUTH_PASSWORD=${{ vars .CLIENT_AUTH_PASSWORD }}"

          # Binance
          echo "BINANCE_BASE_URL=${{ vars .BINANCE_BASE_URL }}"
          echo "BINANCE_API_KEY=${{ vars .BINANCE_API_KEY }}"

          # Supabase
          echo "SUPABASE_CONNECTION_URL=${{ vars .SUPABASE_CONNECTION_URL }}"
          echo "SUPABASE_REST_URL=${{ vars .SUPABASE_REST_URL }}"
          echo "SUPABASE_API_KEY=${{ vars .SUPABASE_API_KEY }}"

      # Debugging: Check contents of .env file
      - name: Check contents of .env
        run: cat .env

      # Step 4: Run your Deno application
      - name: Run Deno main.ts
        run: |
          deno run --allow-env --allow-read --allow-net main.ts
